# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
 - openjdk11

services:
  - postgresql


before_install:
  - psql -c 'create database tracker;' -U postgres

before_script:
#  - psql -c 'create database carsDB;' -U postgres

install:
  mvn install -P travis -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  mvn test -P travis,liquibase,!main -B



# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)


# Отправлять уведомление на почту youremail@smtp.ru(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      voldores@mail.ru
    on_success: never # default: change
    on_failure: always # default: always


env:
  global:
    - CODECOV_TOKEN="2b8846fc-d798-4c70-8708-a32190e385f5"





